/*
* StockSelector

 An application that scraps Morningstar's webpage, picking out stocks that meet a criteria

 install dependencies:

 NPM I

 Run program

 node server.js
*/


let request = require("superagent");
let companiesSandP = "MMM ACE ABT ANF ACN ADBE AMD AES AET AFL A GAS APD ARG AKAM AA ALXN ATI AGN ALL ANR ALTR MO AMZN AEE AEP AXP AIG AMT AMP ABC AMGN APH APC ADI AON APA AIV APOL AAPL AMAT ADM AIZ T ADSK ADP AN AZO AVB AVY AVP BHI BLL BAC BK BCR BAX BBT BEAM BDX BBBY BMS BRK.B BBY BIG BIIB BLK HRB BMC BA BWA BXP BSX BMY BRCM BF.B CHRW CA CVC COG CAM CPB COF CAH CFN KMX CCL CAT CBG CBS CELG CNP CTL CERN CF SCHW CHK CVX CMG CB CI CINF CTAS CSCO C CTXS CLF CLX CME CMS COH KO CCE CTSH CL CMCSA CMA CSC CAG COP CNX ED STZ CBE GLW COST CVH COV CCI CSX CMI CVS DHI DHR DRI DVA DF DE DELL DNR XRAY DVN DV DO DTV DFS DISCA DLTR D RRD DOV DOW DPS DTE DD DUK DNB ETFC EMN ETN EBAY ECL EIX EW EA EMC EMR ESV ETR EOG EQT EFX EQR EL EXC EXPE EXPD ESRX XOM FFIV FDO FAST FII FDX FIS FITB FHN FSLR FE FISV FLIR FLS FLR FMC FTI F FRX FOSL BEN FCX FTR GME GCI GPS GD GE GIS GPC GNW GILD GS GT GOOG GWW HAL HOG HAR HRS HIG HAS HCP HCN HNZ HP HES HPQ HD HON HRL HSP HST HCBK HUM HBAN ITW IR TEG INTC ICE IBM IFF IGT IP IPG INTU ISRG IVZ IRM JBL JEC JDSU JNJ JCI JOY JPM JNPR K KEY KMB KIM KMI KLAC KSS KFT KR LLL LH LRCX LM LEG LEN LUK LXK LIFE LLY LTD LNC LLTC LMT L LO LOW LSI MTB M MRO MPC MAR MMC MAS MA MAT MKC MCD MHP MCK MJN MWV MDT MRK MET PCS MCHP MU MSFT MOLX TAP MON MNST MCO MS MOS MSI MUR MYL NBR NDAQ NOV NTAP NFLX NWL NFX NEM NWSA NEE NKE NI NE NBL JWN NSC NTRS NOC NU NRG NUE NVDA NYX ORLY OXY OMC OKE ORCL OI PCAR PLL PH PDCO PAYX BTU JCP PBCT POM PEP PKI PRGO PFE PCG PM PSX PNW PXD PBI PCL PNC RL PPG PPL PX PCP PCLN PFG PG PGR PLD PRU PEG PSA PHM QEP PWR QCOM DGX RRC RTN RHT RF RSG RAI RHI ROK COL ROP ROST RDC R SWY SAI CRM SNDK SCG SLB SNI STX SEE SHLD SRE SHW SIAL SPG SLM SJM SNA SO LUV SWN SE S STJ SWK SPLS SBUX HOT STT SRCL SYK SUN STI SYMC SYY TROW TGT TEL TE THC TDC TER TSO TXN TXT HSY TRV TMO TIF TWX TWC TIE TJX TMK TSS TRIP TSN TYC USB UNP UNH UPS X UTX UNM URBN VFC VLO VAR VTR VRSN VZ VIAB V VNO VMC WMT WAG DIS WPO WM WAT WPI WLP WFC WDC WU WY WHR WFM WMB WIN WEC WPX WYN WYNN XEL XRX XLNX XL XYL YHOO YUM ZMH ZION";
let NYSE = "PIH TURN FLWS FCCY SRCE VNET TWOU JOBS CAFD EGHT AVHI SHLM AAON ABAX ABEO ABEOW ABIL ABMD AXAS ACIU ACIA ACTG ACHC ACAD ACST AXDX XLRN ANCX ARAY ACRX ACET AKAO ACHN ACIW ACRS ACNB ACOR SQZZ ATVI ACTA ACXM ADMS ADMP ADAP ADUS AEY IOTS ADMA ADBE ADOM ADTN ADRO AAAP ADES AEIS AMD ADXS ADXSW ADVM MAUI AEGN AGLE AEHR AMTX AERI AVAV AEZS AEMD GNMX AFMD AGEN AGRX AGYS AGIO AGNC AGNCB AGNCP AGFS AGFSW AIMT AIRT ATSG AIRG AMCN AKAM AKTX AKBA AKER AKRX AKTS ALRM ALSK AMRI ALBO ABDC ADHD ALDR ALDX ALXN ALCO ALGN ALIM ALJJ ALKS ABTX ALGT AIQ AHGP AMMA ARLP AHPI AMOT ALQA ALLT MDRX AFAM ALNY AOSL GOOG GOOGL SMCP ATEC SWIN AABA ALT ASPS AIMC AMAG AMRN AMRK AYA AMZN AMBC AMBCW AMBA AMCX DOX AMDA AMED UHAL ATAX AMOV AAL ACSF AETI AMNB ANAT AOBC APEI ARII AMRB AMSWA AMSC AMWD CRMT ABCB AMSF ASRV ASRVP ATLO AMGN FOLD AMKR AMPH IBUY ASYS AFSI AMRS ADI ALOG ANAB AVXL ANCB ANDA ANDAR ANDAU ANDAW ANGI ANGO ANIP ANIK ANSS ATRS ANTH ABAC APOG APEN AINV APPF APPN AAPL ARCI APDN APDNW AGTC AMAT AAOI AREX APTI APRI APVO APTO AQMS AQB AQXP ARDM ARLZ PETX ABUS ARCW ABIO RKDA ARCB ACGL ACGLP APLP ARDX ARNA ARCC ARGX AGII AGIIL ARGS ARIS ARKR ARTX ARQL ARRY ARRS DWAT AROW ARWR ARTNA ARTW ASBB ASNA ASND ASCMA APWC ASML AZPN ASMB ASFI ASTE ATRO ALOT ASTC ASUR ASV ATAI ATRA ATHN ATNX ATHX AAPC AAME ACBI ACFC ABY ATLC AAWW AFH AFHBL TEAM ATNI ATOM ATOS ATRC ATRI ATTU LIFE AUBN BOLD AUDC AUPH EARS ABTL ADSK ADP AVDL ATXI AVEO AVXS AVNW AVID AVGR AVIR CAR AHPA AHPAU AHPAW AWRE AXAR AXARU AXARW ACLS AXGN AAXN AXSM AXTI AZRX BCOM RILY RILYL RILYZ BOSC BIDU BCPC BWINA BWINB BLDP BANF BANFP BCTF BKMU BOCH BMRC BMLP BKSC BOTJ OZRK BFIN BWFG BANR BZUN TAPR BHAC BHACR BHACU BHACW BBSI BSET BYBK BV BCBP BECN BSF BBGI BEBE BBBY BGNE BELFA BELFB BLPH BLCM BNCL BNFT BNTC BNTCW BYSI BGCP BGFV BASI ORPN BIOC BCRX BDSI BIIB BIOL BLFS BLRX BMRN BMRA BVXV BVXVW BPTH BIOP BIOS BBC BBP BSTC BSTG BSPM TECH BEAT BIVV BCACU BJRI BBOX BDE BLKB BBRY HAWK BL BKCC ADRA ADRD ADRE ADRU BLMN BCOR BLBD BUFF BHBK BLUE BKEP BKEPP BPMC ITEQ BMCH BOBE BOFI BOFIL WIFI BOJA BOKF BOKFL BNSO BOMN BPFH BPFHP BPFHW EPAY BLVD BLVDU BLVDW BCLI BBRG BDGE BLIN BRID BCOV AVGO BSFT BVSN BYFC BWEN BRCD BRKL BRKS BRKR BMTC BLMT BSQR BWLD BLDR BMLA BUR CFFI CHRW CA CCMP CDNS CDZI CACQ CZR CSTE PRSS CLBS CHY CHI CCD CHW CGO CSQ CAMP CVGW CFNB CALA CALD CALM CLMT ABCD CAC CAMT CSIQ CGIX CPHC CPLA CBF CCBG CPLP CSWC CPTA CPTAG CPTAL CLAC CLACU CLACW CFFN CAPR CSTR CPST CARA CARB CCN CRME CSII CATM CDNA CECO CTRE CARO CART CRZO TAST CRTN CARV CASM CASC CWST CASY CASI CASS CATB CBIO CPRX CATS CATY CATYW CVCO CAVM CBFV CBAK CBOE CDK CDW CECE CELG CELGZ CLDX APOP APOPW CLRB CLRBW CLRBZ CLLS CBMG CLSN CELH CYAD CEMP CETX CETXP CETXW CDEV CSFL CETV CFBK CENT CENTA CVCY CENX CNBKA CNTY CRNT CERC CERCW CERN CERU CERS KOOL CEVA CFCO CFCOU CFCOW CSBR CYOU HOTR CTHR GTLS CHTR CHFN CHKP CHEK CHEKW CEMI CHFC CCXI CHMG CHKE CHFS CHMA PLCE CMRX CADC CALI CAAS CBPO CCCL CCCR CCRC JRJC HGSH CNIT CJJD CLDC HTHT CHNR CREG CNTF CXDC CCIH CNET IMOS CDXC CHSCL CHSCM CHSCN CHSCO CHSCP CHDN CHUY CDTX CMCT CMPR CINF CIDM CTAS CRUS CSCO CTRN CZNC CZWI CZFC CIZN CTXS CHCO CIVB CIVBP CDTI CLNE CLNT CACG YLDE LRGE CLFD CLRO CLSD CLIR CLIRW CBLI CSBK CLVS CMFN CME CCNE CWAY COBZ COKE CDXS CVLY JVA CCOI CGNT COGT CGNX CTSH COHR CHRS COHU CLCT COLL CIGI CBAN COLB COLM CMCO CBMX CBMXW CMCSA CBSH CBSHP CUBN CHUBA CHUBK CVGI COMM JCS ESXB CFBI CYHHZ CTBI CWBC CVLT CGEN CPSI CTG CHCI CMTL CNAT CNCE CXRX CCUR CDOR CFMS CNFR CNMD CTWS CNOB CNXR CONN CNSL CWCO CNACU CPSS CFRX CTRV CTRL CPAA CPAAU CPAAW CPRT CRBP CORT CORE CORI CSOD CRVL CRVS CSGP COST CPAH ICBK COUP CVTI COVS COWN COWNL PMTS CPSH CRAI CBRL BREW CRAY CACC USOI CREE CRESY CRSP CRTO CROX CCRN CRDS CRWS CYRX CYRXW CSGS CCLP CSPI CSWI CSX CTIC CTIB CTRP CUNB CUI CPIX CMLS CRIS CUTR CVBF CVV CYAN CYBR CYBE CYCC CYCCP CBAY CY CYRN CONE CYTK CTMX CYTX CYTXW CTSO CYTR DJCO DAKT DRIO DRIOW DZSI DSKE DSKEW DAIO DRAM DWCH PLAY DTEA DFNL DUSA DWLD DWSN DBVT DFRG TACO TACOW DCTH DMPI DGAS DELT DELTW DENN XRAY DEPO DERM DEST DXLG DSWL DTRM DXCM DXTR DHXM DHIL FANG DCIX DRNA DFBG DFFN DGII DGLT DMRC DRAD DGLY APPS DCOM DMTX DIOD DISCA DISCB DISCK DISH DVCR SAUC DLHC BOOM DNBF DLTR DGICA DGICB DMLP DORM EAGL EAGLU EAGLW DRWI DRYS DSPG DLTH DNKN DRRX DXPE DYSL DYNT DVAX ETFC EBMT EGBN EGLE EGRX EWBC EACQ EACQU EACQW EML EVBS EVGBC EVSTC EVLMC EBAY EBAYL EBIX ELON ECHO SATS EEI ESES EDAP EDGE EDGW EDIT EDUC EGAN EGLT EHTH EIGR EKSO LOCO EMITF ESLT ERI ESIO EA EFII ELSE ELEC ELECU ELECW EBIO DWAC ESBK ELTK EMCI EMCF EMKR EMMS NYNY ENTA ECPG WIRE ENDP ECYT ELGX NDRA NDRAU NDRAW EIGI WATT EFOI ERII EXXI ENOC ENG ENPH ESGR ENFC ENTG ENTL ETRM EBTC EFSC ENZY EPZM PLUS EQIX EQFN EQBK ERIC ERIE ESCA ESPR ESSA EPIX ESND ETSY CLWT EEFT ESEA EVEP EVBG EVK MRAM EVLV EVGN EVOK EVOL EXA EXAS EXAC EXEL EXFO EXLS EXPE EXPD EXPO ESRX XOG EXTR EYEG EYEGW EZPW FFIV FB FRP FALC DAVE FANH FARM FMAO FFKT FMNB FARO FAST FATE FBSS FNHC FHCO FENX GSM FCSC FGEN ONEQ LION FDUS FRGI FSAM FSC FSCFL FSFR FITB FITBI FNGN FISI FNSR FNJN FNTE FNTEU FNTEW FEYE FBNC FNLC FRBA BUSE FBIZ FCAP FCFS FCNCA FCBC FCCO FCFP FBNK FDEF FFBC FFBCW FFIN THFF FFNW FFWM FGBI FHB INBK INBKL FIBK FRME FMBH FMBI FNWB FSFG FSLR FSBK FAAR FPA BICK FBZ FCAL FCAN FTCS FCEF FCA SKYY RNDM FDT FDTS FVC FV IFV FEM RNEM FEMB FEMS FTSM FEP FEUZ FGM FTGC FTHI HYLS FHK FTAG FTRI FPXI YDIV FJP FEX FTC RNLC FTA FLN FTLB LMBS FMB FMK FNX FNY RNMC FNK FAD FAB MDIV MCEF QABA FTXO QCLN GRID CIBR FTXG CARZ FTXN FTXH FTXD FTXL FONE TDIV FTXR QQEW QQXT QTEC AIRR QINC RDVY RFAP RFDI RFEM RFEU FTSL FYX FYC RNSC FYT FKO FCVT FDIV FSZ FTW FIXD TUSA FKU RNDV FUNC FUSB SVVC FSV FISV FIVE FPRX FVE FIVN FLEX FLKS FLXN SKOR LKOR MBSD ASET ESGG ESG QLC FPAY FLXS FLIR FLDM FFIC FNBG FOMX FOGO FONR FRSX FH FORM FORTY FORR FRTA FTNT FBIO FMCI FMCIR FMCIU FMCIW FWRD FORD FWP FOSL FMI FOXF FRAN FELE FKLYU FRED RAIL FEIM FRPT FTEO FTR FTRPR FRPH FSBW FSBC FTD FTEK FCEL FLGT FORK FLL FULT FSNN FTFT FFHL WILC GTHX FOANC MOGLC GAIA GLPG GALT GALE GLMD GLPI GPIC GRMN GARS GDS GEMP GENC GNCMA GFN GFNCP GFNSL GENE GNUS GNMK GNCA GHDX GNTX THRM GEOS GABC GERN GEVO ROCK GIGM GIGA GIII GILT GILD GBCI GLAD GLADO GOOD GOODM GOODO GOODP GAIN GAINM GAINN GAINO LAND LANDP GLBZ GBT GLBR ENT GBLI GBLIL GBLIZ GPAC GPACU GPACW SELF GSOL GWRS KRMA FINX ACTX BFIT SNSR LNGR MILN EFAS QQQC BOTZ CATH SOCL ALTY SRET YLCO GLBS GLUU GLYC GOGO GLNG GMLP GDEN GOGL GBDC GTIM GPRO GSHT GSHTU GSHTW GOV GOVNI GPIA GPIAU GPIAW LOPE GRVY FULLL GECC GEC GLDD GSBC GNBC GRBK GPP GPRE GCBC GLRE GSUM GRIF GRFS GRPN OMAB GGAL GSIT GSVC GTXI GTYH GTYHU GTYHW GBNK GNTY GFED GUID GIFI GURE GPOR GWPH GWGH GYRO HEES HLG HNRG HALL HALO HBK HLNE HBHC HBHCL HNH HAFC HQCL HONE HDNG HLIT HRMN HRMNU HRMNW HBIO HCAP HCAPL HAS HA HCOM HWKN HWBK HAYN HDS HIIQ HCSG HQY HSTM HTLD HTLF HTBX HEBT HSII HELE HMNY HMTV HNNA HSIC HTBK HFWA HCCI MLHR HRTX HSKA HIBB SNLN HPJ HIHO HIMX HIFS HSGX HMNF HMSY HOLI HOLX HBCP HOMB HFBL HMST HMTA HTBI HOFT HOPE HFBC HBNC HZNP HRZN DAX QYLD HDP HPT TWNK TWNKW HMHC HWCC HOVNP HBMD HSNI HTGM HUBG HSON HDSN HUNT HUNTU HUNTW HBAN HBANN HBANO HBANP HURC HURN HCM HBP HVBC HYGS IDSY IAC IBKC IBKCO IBKCP ICAD IEP ICCH ICFI ICHR ICLR ICON ICUI IPWR INVE IDRA IDXX IESC IROQ IFMK RXDX INFO IIVI KANG IKNX ILG ILMN ISNS IMMR ICCC IMDZ IMNP IMGN IMMU IMRN IMRNW IPXL IMPV PI IMMY INCR INCY INDB IBCP IBTX IDSA INFN INFI IPCC III IFON IMKTA INWK INNL INOD IPHS IOSP ISSC INVA INGN ITEK INOV INO INPX INSG NSIT ISIG INSM INSE IIIN PODD INSY NTEC IART IDTI INTC NTLA IPCI IPAR IBKR ICPT IDCC TILE LINK IMI INAP IBOC ISCA IGLD IIJI IDXG XENT INTX IVAC INTL ITCI IIN INTU ISRG SNAK ISTR ISBC ITIC NVIV IVTY IONS IPAS DTYS DTYL DTUS DTUL DFVS DFVL FLAT DLBS DLBL STPP IPGP CSML IRMD IRTC IRIX IRDM IRDMB IRBT IRWD IRCP PMPT SLQD TLT AIA COMT IXUS FALN IFEU IFGL IGF GNMA HYXE JKI ACWX ACWI AAXJ EWZS MCHI ESGD SCZ ESGE EEMA EUFN IEUS MPCT ENZL QAT UAE ESGU IBB SOXX EMIF ICLN WOOD INDY ISHG IGOV ISRL ITI ITRI ITRN ITUS IVENC IVFGC IVFVC IXYS IZEA JJSF MAYS JBHT JCOM JASO JKHY JACK JXSB JAGX JAKK JMBA JRVR SGQI JSML JSMD JASN JASNW JAZZ JD JSYN JSYNR JSYNU JSYNW JBLU JTPY JCTCF WYIG WYIGU WYIGW JMU JBSS JOUT JNCE JNP JUNO KTWO KALU KALV KMDA KNDI KPTI KAAC KAACU KAACW KBLMU KBSF KCAP KRNY KELYA KELYB KMPH KFFB KERX KEQU KTEC KTCC KFRC KE KBAL KIN KGJI KINS KONE KNSL KIRK KITE KTOV KTOVW KLAC KLXI KONA KOPN KRNT KOSS KWEB KTOS KLIC KURA KVHI FSTR LJPC LSBK LBAI LKFN LAKE LRCX LAMR LANC LCA LCAHU LCAHW LNDC LARK LMRK LMRKO LMRKP LE LSTR LNTH LTRX LSCC LAUR LAWS LAYN LCNB LBIX LPTX LGCY LGCYO LGCYP LTXB DDBI EDBI INFR LVHD UDBI LMAT TREE LXRX LGIH LHCG LLIT LBRDA LBRDK LEXEA LEXEB LBTYA LBTYB LBTYK LILA LILAK LVNTA LVNTB QVCA QVCB BATRA BATRK FWONA FWONK LSXMA LSXMB LSXMK TAX LTRPA LTRPB LPNT LCUT LFVN LWAY LGND LTBR LPTH LLEX LMB LLNW LMNR LINC LECO LIND LINDW LINU LBIO LPCN LQDT LFUS LIVN LOB LIVE LPSN LKQ LMFA LMFAW LMIA LOGI LOGM EVAR CNCR LONE LTEA LORL LOXO LPLA LRAD LYTS LULU LITE LMNX LMOS LUNA MBTF MACQ MACQU MACQW MIII MIIIU MIIIW MBVX MCBC MFNC MTSI MGNX MDGL MAGS MGLN MGIC CALL MNGA MGYR MHLD MSFG MMYT MBUU MLVF MAMS TUSK MANH LOAN MNTX MTEX MNKD MANT MARA MCHX MARPS MRNS MKTX MRLN MAR MBII MRTN MMLP MRVL MASI MTCH MTLS MPAC MPACU MPACW MTRX MAT MATR MATW MXIM MXPT MXWL MZOR MBFI MBFIP MCFT MGRC MDCA MFIN MFINL MTBC MTBCP MNOV MDSO MDGS MDWD MDVX MDVXW MEDP MEIP MLCO MLNX MELR MTSL MELI MBWM MERC MRCY EBSB VIVO MRDN MRDNW MMSI MACK MSLI MRUS MLAB MESO CASH MEOH MGCD MGEE MGPI MBOT MCHP MU MICT MICTW MSCC MSFT MSTR MVIS MPB MTP MCEP MBCN MSEX MSBI MOFG MIME MDXG MNDO MB NERV MGEN MRTX MIRN MSON MIND MINDP MITK MITL MKSI MMAC MINI MOBL MMDM MMDMR MMDMU MMDMW MLNK MBRX MNTA MOMO MCRI MDLZ MGI MPWR TYPE MNRO MRCC MNST MSDI MSDIW MORN MOSY MOTA MOTAW MTFB MTFBW MPAA MPVD MOXC MRVC MSBF MSG MTGE MTGEP MTSC LABL MFSF MYSZ MYL MYOK MYOS MYRG MYGN NBRV NAKD NNDM NANO NSTG NH NK NSSC NDAQ NTRA NATH NAUH NKSH FIZZ NCMI NCOM NESR NESRW NGHC NGHCN NGHCO NGHCP NGHCZ NHLD NHLDW NATI NRCIA NRCIB NSEC NWLI NAII NHTC NATR BABY ISM JSM NAVI NBTB NCIT NCSM NKTR NEOG NEO NEON NEOS NEOT NVCN NEPT UEPS NETE NTAP NTES NFLX NTGR NLST NTCT NTWK CUR NBIX NDRM NURO NUROW NTRP NBEV NYMT NYMTO NYMTP NLNK NWS NWSA NEWS NEWT NEWTL NEWTZ NXEO NXEOU NXEOW NXST NVET NFEC NODK EGOV NICE NICK NCBS NIHD NVLS NMIH NNBR NDLS NDSN NSYS NBN NTIC NTRS NTRSP NFBK NRIM NWBI NWPX NCLH NWFL NVFY NVMI NVDQ NOVN NOVT NVAX NVLN NVCR NVGN NVUS NUAN NMRX NTNX NUTR NTRI NUVA NVTR QQQX NVEE NVEC NVDA NXPI NXTM NXTD NXTDW NYMX OIIM OVLY OASM OBLN OBSV OBCI OPTT ORIG OCFC OCRX OCLR OFED OCUL OMEX ODP OFS OHAI OVBC OHRP OKTA ODFL OLBK ONB OPOF OSBC OSBCP OLLI ZEUS OFLX OMER OMNT OMCL ON OTIV ONS ONSIW ONSIZ OGXI OMED ONTX ONTXW ONCS OHGI ONVI OTEX OPXA OPXAW OPGN OPGNW OPHT OPK OBAS OCC OPHC OPB ORMP OSUR ORBC ORBK ORLY OREX ONVO SEED OACQ OACQR OACQU OACQW OESX ORIT ORRF OFIX OSIS OSN OTEL OTIC OTTW OTTR OVAS OSTK OVID OXBR OXBRW OXFD OXLC OXLCM OXLCN OXLCO PFIN PTSI PCAR PACB PCBK PEIX PMBC PPBI PAAC PAACR PAACU PAACW PCRX PACW PTIE PAAS PNRA PANL PZZA FRSH PBNC PRTK PRXL PCYG PSTB PKBK PRKR PKOH PTNR PBHC PATK PNBK PATI PEGI PDCO PTEN PAVM PAVMW PAYX PCTY PYDS PYPL PBBI CNXN PCMI PCSB PCTI PDCE PDFS PDLI PDVW SKIS PGC PEGA PCO PENN PVAC PFLT PNNT PWOD PTXP PEBO PEBK PFBX PFIS PBCT PBCTP PUB PRCP PPHM PPHMP PRFT PFMT PERF PERI PESI PPIH PTX PERY PGLC PETS PFSW PGTI PZRX PHII PHIIK PAHC PHMD PLAB PICO PIRS PPC PME PNK PNFP PPSI PXLW PLPM PLYA PLYAW PLXS PLUG PLBC PSTI PLXP PBSK PNTR PCOM POLA COOL POOL POPE BPOP BPOPM BPOPN PBIB PTLA PBPB PCH POWL POWI PLW PKW PFM PYZ PEZ PSL PIZ PIE PXI PFI PTH PRN DWLV PDP DWAQ DWAS DWIN DWTR PTF PUI IDLB PRFZ PAGG PSAU PIO PGJ PEY IPKW PID KBWB KBWD KBWY KBWP KBWR LDRI LALT PNQI PDBC QQQ USLB PSCD PSCC PSCE PSCF PSCH PSCI PSCT PSCM PSCU VRIG PHO PRAA PRAH PRAN PFBC PLPC PFBI PINC LENS PSDO PRGX PSMT PBMD PNRG PRMW PRIM BTEC GENY PSET PY PSC PDEX IPDN PFIE PGNX PRGS PFPT PRPH PRQR BIB UBIO TQQQ ZBIO SQQQ BIS PSEC PTGX PRTO PTI PRTA PVBC PROV PBIP PSDV PMD PTC PTCT PULM PLSE PBYI PCYO IMED FINQ PXS QADA QADB QCRH QGEN QIWI QRVO QCOM QSII QBAK QLYS QTNA QTRH QRHC QUIK QDEL QPAC QPACU QPACW QNST QUMU QTNT RRD RCM RARX RADA RDCM RSYS RDUS RDNT RDWR METC RMBS RAND RLOG GOLD RNDB RPD RAVE RAVN ROLL RICK RCMT RDI RDIB RGSE RELY RNWK RP RETA RCON REPH RRGB RRR RDHL REGN RGNX RGLS REIS RELV MARK RNST REGI RNVA RNVAZ RCII RTK RGEN RPRX RBCAA FRBK REFR RESN RECN ROIC RTRX RVNC RVEN RVLT RWLK REXX RFIL RGCO RIBT RIBTW RELL RIGL NAME RNET RTTR RVSB RLJE RMGN ROBO FUEL RMTI RCKY RMCF ROKA RTNB ROSE ROSEU ROSEW ROSG ROST RBPAA RGLD RPXC RTIX RBCN RUSHA RUSHB RUTH RXII RXIIW RYAAY STBA SANW SCAC SCACU SCACW SBRA SBRAP SABR SAEX SAFT SAGE SAIA SAJA SALM SAL SAFM SASR SGMO SANM GCVRZ SPNS SRPT SVRA SBFG SBFGP SBAC SCSC SMIT SCHN SCHL SCLN SGMS SNI SCYX SEAC SBCF STX SHIP SHIPW SRSC SHLD SHLDW SHOS SPNE SGEN EYES EYESW SCWX SNFCA SEIC SLCT SCSS SIR SELB SIGI LEDS SMTC SENEA SENEB SNES SNH SNHNI SNHNL SNMX SRTS SRTSW SQBG MCRB SREV SFBS SEV SVBI SGBX SGOC SMED SHSP SHEN SHLO TYHT SHPG SCVL SHBI SHOR SSTI SFLY SIFI SIEB SIEN BSRR SRRA SWIR SIFY SIGM SGLB SGLBW SGMA SBNY SBNYW SLGN SILC SLAB SIMO SPIL SRUN SRUNU SRUNW SSRI SAMG SSNT SFNC SLP SINA SBGI SINO SVA SIRI SITO SKYS SKLN SKYW SWKS SLM SLMBP SGH SND SMBK SMSI SMTX LNCE SRAX SCKT SODA SOHU SLRC SUNS SEDG SLNO SLNOW SNGX SNGXW SONC SOFO SNOA SNOAW SONS SPHS SORL SRNE SOHO SOHOB SOHOM SFBC SSB SFST SMBC SONA SBSI OKSB SP SGRP SPKE SPKEP ONCE SPAR SPTN DWFI SPPI ANY SPEX SPI SAVE SPLK SPOK SPWH SBPH FUND SFM SPSC SSNC STAA STAF STMP STLY SPLS SBLK SBLKL SBUX STFC STBZ SNC STDY GASS STLD SMRT STLR STLRU STLRW SBOT STML SRCL SRCLP STRL SHOO SSFN SYBT BANX SGBK SSKN SSYS STRT STRS STRA STRM SBBP STB SCMP SUMR SMMF SSBI SMMT SNBC SNHY SNDE SNSS STKL SPWR RUN SBCP SUNW SMCI SPCB SCON SGC SUPN SPRT SGRY SRDX SBBX SIVB SIVBO SYKE SYMC SYNC SYNL SYNA SNCR SNDX SGYP ELOS SNPS SYNT SYMX SYPR SYRS TROW TTOO TRHC TCMD TAIT TTWO TLND TNDM TLF TANH TPIV TEDU TATT TAYD CGBD TCPC AMTD TEAR TECD TCCO TTGT TGLS TGEN TNAV TTEC TLGT TELL TENX GLBL TERP TVIA TBNK TSRO TESO TSLA TESS TTEK TTPH TCBI TCBIL TCBIP TCBIW TXN TXRH TFSL TGTX ABCO ANDE TBBK BONT CG CAKE CHEF TCFC DSGX DXYN ENSG XONE FINL FBMS FLIC GT HABT HCKT HAIN FITS CUBA INTG JYNT KEYW KHC OLD MDCO MEET MIK MIDD NAVG SLIM STKS ORG PCLN PRSC RMR SPNC TTD ULTI YORW NCTY TRPX TBPH TST TCRD THLD TICC TICCL TIG TTS TIL TSBK TIPT TITN TTNP TVTY TIVO TMUS TMUSP TOCA TNXP TISA TOPS TORM TRCH TSEM CLUB TOWN TPIC TCON TSCO TWMC TACT TRNS TGA TA TANNI TANNL TANNZ TZOO TRVN TCBK TRIL TRS TRMB TRIB TRIP TSC TBK TRVG TRNC TROV TRUE THST TRUP TRST TRMK TSRI TTMI TCX TUES TOUR HEAR TUTI TUTT FOX FOXA TWIN TRCB USCR PRTS USEG GROW UBNT UFPT ULTA UCTT UPL RARE ULBI UMBF UMPQ UNAM UBSH UNB UNXL QURE UBCP UBOH UBSI UCBA UCBI UCFC UBNK UFCS UIHC UNFI UBFO USLM UTHR UG UNIT UNTY OLED UEIC UFPI ULH USAP UVSP UPLD URRE UONE UONEK URBN URGN ECOL USAT USATP USAK UTMD UTSI VLRX VALX VALU VNDA BBH GNRX PPH VWOB VNQI VGIT VCIT VIGI VYMI VCLT VGLT VMBS VONE VONG VONV VTWO VTWG VTWV VTHR VCSH VGSH VTIP BNDX VXUS VEAC VEACU VEACW VREX VRNS VDSI VBLT VBIV WOOF VECO DGLD DSLV UGLD USLV TVIZ TVIX ZIV XIV VIIZ VIIX VEON VRA VCYT VSTM VCEL VRNT VRSN VRSK VBTX VERI VRML VRNA VSAR VTNR VRTX VIA VIAB VSAT VIAV VICL VICR CIZ VSDA CEZ CID CIL CFO CFA CSF CDC CDL VSMV CSB CSA VBND VUSE VIDI VDTH VRAY VKTX VKTXW VBFC VLGEA VNOM VIRC VIRT VRTS VRTSP VRTU VTGN VTL VIVE VVPR VVUS VOD VOXX VYGR VSEC VTVT VUZI VWR WBA WAFD WAFDW WASH WFBI WSBF WVE WAYN WSTG WCFB WDFC FLAG WEB WBMD WCST WB WEBK WEN WERN WSBC WTBA WSTC WMAR WABC WBB WSTL WDC WNEB WLB WPRT WEYS WHLR WHLRD WHLRP WHLRW WHF WHFBL WFM WHLM WVVI WVVIP WLDN WLFC WLTW WIN WING WINA WINS WTFC WTFCM WTFCW AGZD AGND CXSE EMCG EMCB DGRE DXGE HYZD WETF DXJS GULF HYND CRDT DGRW DGRS DXPS UBND WIX WMIH WBKC WWD WKHS WRLD WPCS WPPGY WMGI WMGIZ WSFS WSFSL WSCI WVFC WYNN XBIT XELB XCRA XNCR XBIO XBKS XENE XGTI XGTIW XLNX GLDI SLVO XOMA XPER XPLR XTLB XNET YNDX YERR YTRA YTEN YIN YGYI YRCW YECO YY ZFGN ZAGG ZAIS ZBRA Z ZG ZN ZNWAA ZION ZIONW ZIONZ ZIOP ZIXI ZGNX ZSAN ZUMZ ZYNE ZNGA ";
let AMEX = "XXII FAX IAF CH ABE FCO IF ISL ACU AIII ATNM AE ADK ADK^A ACY AIRI AXU ALO AAU APT AAMC DIT ALN AMS USAS AMPE APHB AXN ARNC^ AKG AINC ASB.WS AST AST.WS AUXO AWX ASM BTG BTN BKJ BCV BCV^A BAA BHB BRN BGSF BPMX BTX BTX.WS BGI BZM MHE BLE BLJ BFY BHV BDR BRG BRG^A BRG^C BRG^D BVX BWL.A BTI CEI CANF ROX CAW CVM CVM.WS CEF CET LEU CCF CQH CQP LNG CVR CPHI CKX GLV GLQ GLO MOC CIX LODE CTO MCF CUO CMT CVRS CRMD CRF CLM CVU CIK DHY CRHM CRVP DXR VCF VFL VMM DLA DNN DGSE DPW DSS DMF GRF EVM EIA CEV EVV MAB MMV MIW EMI EIM EIV EMJ EVJ ENX NYH EVY EIO EVO EIP EVP ELMD ELLO ECF EMAN MSN UUUU UUUU.WS ENRJ ENSV ESNC EGI EVI ERN ESP EMX EVBN EPM XRA FPP FPP.WS FEN BDL FSI FTF FSP FRD GGN GGN^B EGAS GST GST^A GST^B JOB GMO GSB GSAT GLOW GORO GSV AUMN GSS GV GDP GTE GPL SIM GVP HEB HLM^ HMG HUSA IBIO IBO IEC IMUC IMUC.WS IMH IMO IOT IRT IGC INFU IHT NSPR NSPR.WS NSPR.WS.B IFMI IDN INS THM INTT INUV VKI ISR ISDR JRJR KIQ KLDX LTS LTS^A LAQ LGL LBY LLEX LIQT MAG MJCO MHH MTNB IPB MXC CCA MICR MLSS MVF MZA MYO NNVC ATEST ATEST.A ATEST.B ATEST.C NHC NAVB NTIP NBW NHS NBH NML NBO NRO UWN NSU GBR NEN NGD NXE HLTH NSAT NAK NOG NBY NG NTN NJV NPN OCX OGEN TIS ONP ORM PHF PCG^A PCG^B PCG^C PCG^D PCG^E PCG^G PCG^H PCG^I PTN PARR PZG TEUM PRK PED PFNX HNW PLG PLYM PLM PW PW^A PLX RLGT RLGT^A UTG REED RWC RCG RVP RNN REI RIF SACH SGA SSN SNMP SAND SEB SENS SVT SIF SVM SKY XPL SCE^B SCE^C SCE^D SCE^E SGB LOV SRCI SGY.WS STRP SSY SDPI STS SYN TKAT TRX TGB TIK TGC GLU GLU^A GGO GGO^A TXMD TMP TAT TRXC TMQ TPHS TRT HTM UFAB UAMY UUU UQM URG UEC VSR VII VHC VGZ VNRX VISI EAD ERC ERH SBI WRN WYY WTT XTNT YUMA ZDGE ";
let companies = companiesSandP + NYSE + AMEX;
let arrayOfCompanies = companies.split(" ");
let fs = require("fs");
const Throttle = require('superagent-throttle');
let throttle = new Throttle({
    active: true,     // set false to pause queue
    rate: 1000,          // how many requests can be sent every `ratePer`
    ratePer: 1000,   // number of ms in which `rate` requests may be sent
    concurrent: 2     // how many requests can be sent concurrently
});

/*
 * Criteria:
 * free cashflow must be positive
 * return on equity: >12%
 * return on assets: >8%
 * Net profit margin: must be positive
 */

//default params, increase to make more strict or vice versa
let ROE = 12;
let ROA = 8;
let NPM = 0;


function makeRequest(symbol)
{
    request
        .get("http://financials.morningstar.com/ajax/exportKR2CSV.html?t=" + symbol)
        .use(throttle.plugin())
        .end((err, data) =>
        {
            try
            {
                let result = data.text;
                if(result == "We’re sorry. There is no available information in our database to display."
                    || result.includes("502 Proxy Error" || result.includes("Morningstar.com Error Page"))) return;

                let resultArray = result.split("\n");

                for(let i =0; i < resultArray.length; i++)
                {
                    if(resultArray[i].includes("Free Cash Flow/Net Income") && resultArray[i].includes("-"))
                    {
                        return;
                    }
                    else if(resultArray[i].includes("Return on Equity"))
                    {
                        if(!filterByCriteria(resultArray[i], ROE)) return;
                    }
                    else if(resultArray[i].includes("Return on Assets"))
                    {
                        if(!filterByCriteria(resultArray[i], ROA)) return;
                    }
                    else if(resultArray[i].includes("Net Margin %"))
                    {
                        //must be positive i.e. greater than 0
                        if(!filterByCriteria(resultArray[i], NPM)) return;
                    }
                }
                //if it passes all the criteria then write to file
                writeToFile(result, symbol);
            }
            catch(exception)
            {
                console.log(exception);
            }

        });
}


function getDataOnCompanies()
{
    for(company of arrayOfCompanies)
    {
        //limits requests so that the api won't seize up
        let symbol = company.replace(" ", "");
        makeRequest(symbol);
    }
}

function writeToFile(text, symbol)
{
    console.log("company passes, symbol is: " + symbol);
    if(text.trim() == "") return;
    fs.writeFile("./companies/" + symbol + ".txt", text, function(err)
    {
        if(err) console.log(err);
        else console.log("company information saved to file");
    });
}

function filterByCriteria(results, requirement)
{
    let filteredResult = results.replace(/[^0-9.]/g, " ");
    let noWhiteSpace = filteredResult.toString().trim();
    let filteredNumbers = noWhiteSpace.split(" ");

    for(i=0; i < filteredNumbers.length; i++)
    {
        if(filteredNumbers[i] < requirement)
        {
            return false;
        }
    }
    return true;
}

getDataOnCompanies();